### ISSUE TITLE
Uncaught Error: Typed property Overtrue\PHPLint\Linter::$processCallback

### ISSUE THREAD

**Issue by olegpro** [overtrue/phplint#100]
For PHP 8.0.8 with parameter --no-progress:

```
$ vendor/bin/phplint --no-cache --no-progress

phplint 3.0 by overtrue and contributors.

Loaded config from "/app/.phplint.yml"

Checking...PHP Fatal error:  Uncaught Error: Typed property Overtrue\PHPLint\Linter::$processCallback must not be accessed before initialization in /app/vendor/overtrue/phplint/src/Linter.php:37
Stack trace:
#0 /app/vendor/overtrue/phplint/src/Command/LintCommand.php(277): Overtrue\PHPLint\Linter->lint(Array, false)
#1 /app/vendor/overtrue/phplint/src/Command/LintCommand.php(163): Overtrue\PHPLint\Command\LintCommand->executeLint(Object(Overtrue\PHPLint\Linter), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), 274)
#2 /app/vendor/symfony/console/Command/Command.php(299): Overtrue\PHPLint\Command\LintCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /app/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /app/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand(Object(Overtrue\PHPLint\Command\LintCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /app/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /app/vendor/overtrue/phplint/bin/phplint(32): Symfony\Component\Console\Application->run()
#7 {main}
  thrown in /app/vendor/overtrue/phplint/src/Linter.php on line 37

Fatal error: Uncaught Error: Typed property Overtrue\PHPLint\Linter::$processCallback must not be accessed before initialization in /app/vendor/overtrue/phplint/src/Linter.php:37
Stack trace:
#0 /app/vendor/overtrue/phplint/src/Command/LintCommand.php(277): Overtrue\PHPLint\Linter->lint(Array, false)
#1 /app/vendor/overtrue/phplint/src/Command/LintCommand.php(163): Overtrue\PHPLint\Command\LintCommand->executeLint(Object(Overtrue\PHPLint\Linter), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), 274)
#2 /app/vendor/symfony/console/Command/Command.php(299): Overtrue\PHPLint\Command\LintCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /app/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /app/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand(Object(Overtrue\PHPLint\Command\LintCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /app/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /app/vendor/overtrue/phplint/bin/phplint(32): Symfony\Component\Console\Application->run()
#7 {main}
  thrown in /app/vendor/overtrue/phplint/src/Linter.php on line 37

```

Without parameter --no-progress its ok.

**Comment by overtrue** [comment]
Please upgrade to 3.0.3 to fix it. https://github.com/overtrue/phplint/releases/tag/3.0.3
